# Generated by Django 5.0.3 on 2024-03-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
    ]
